name: firebase_list
version: 0.0.0
author: Christopher Best <bestchris@gmail.com>
description: Implementation of a list synced to a firebase location
homepage: https://github.com/sirctseb/FirebaseList
environment:
  sdk: '>=1.8.0 <2.0.0'
documentation: http://sirctseb.github.io/FirebaseList
dependencies:
  firebase: ^0.6.3
dev_dependencies:
  test: ^0.12.4
  logging: ^0.11.2
  logging_handlers: ^0.8.0
